config/routes.rb
ExpenseAppServer::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'
  get  'welcome/signup', as: 'signup'
  post 'welcome/complete_signup' ,as: 'complete_signup'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :accounts
  resources :shared_transactions do
    get :shared, on: :collection
    get :to_pay, on: :collection
    get :to_be_paid, on: :collection
    post :pay_bill, on: :collection
    post :confirm_payment, on: :collection
  end

  resources :transactions do
    get :expenses, on: :collection
    get :incomes, on: :collection
    get :shared, on: :collection
    get :overview, on: :collection
  end
  resources :vendors
  resources :users

  

end

app/models/transaction_type.rb
# == Schema Information
#
# Table name: transaction_types
#
#  id           :integer          not null, primary key
#  display_name :string(255)      not null
#  created_at   :datetime
#  updated_at   :datetime
#

class TransactionType < ActiveRecord::Base
  has_many :transactions
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :require_authentication, unless: :format_json
  before_filter :require_email, unless: :format_json

  def index
    user_id = session[:user_id] || User.find_by(twitter_user_name: params[:username]).try(:id)
    if user_id
      @transactions = Transaction.where(user_id: user_id).order("transaction_date")
      @jsonTransactions = Transaction.to_jsonFormat(@transactions)
      @jsonArr = {"transactions" => @jsonTransactions}
    end
    respond_to do |format|
      format.html {}
      format.json {render json: @jsonArr || "Sorry" }
    end
  end
  
  def new
  end

  def create
    user_id = session[:user_id] || User.find_by(twitter_user_name: params[:username]).try(:id)
    if user_id.present?
      transaction = Transaction.create_new_transaction(params, user_id)
      if transaction.is_a?(String)
        notice = transaction
        redirect = new_account_path
      elsif transaction.is_a?(Transaction)
        notice = "Your Transaction added Successfully"
        redirect = transactions_path
      end
      respond_to do |format|
        format.html {redirect_to redirect, notice: notice}
        format.json {render json: notice}
      end
      
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def overview
    user_id = get_user
    if user_id.present?
      expenses = Transaction.get_total_of("Expense", user_id)
      incomes = Transaction.get_total_of("Income", user_id)
      to_pay = SharedTransaction.where("user_id = :uid and owner_id <> :uid", uid: user_id).sum(:amount)
      to_be_paid = SharedTransaction.where("user_id <> :uid and owner_id = :uid", uid: user_id).sum(:amount)    
      shared = to_be_paid - to_pay
    end
    @overview = {expenses: expenses, incomes: incomes, to_pay: to_pay, to_be_paid: to_be_paid, shared: shared}
    respond_to do |format|
      format.html {}
      format.json {render json: @overview || "Sorry" }
    end    
  end

  def expenses
    user_id = get_user
    if user_id.present?
     @jsonTransactions = Transaction.getTransactionbyType(user_id, "Expense")
     @jsonArr = {"transactions" => @jsonTransactions}
    end
    respond_to do |format|
      format.html {}
      format.json {render json: @jsonArr || "Sorry" }
    end
  end

  def shared
    user_id = get_user
    if user_id.present?
     @jsonTransactions = Transaction.getTransactionbyType(user_id, "Shared")
     @jsonArr = {"transactions" => @jsonTransactions}
    end
    respond_to do |format|
      format.html {}
      format.json {render json: @jsonArr || "Sorry" }
    end
  end

  def incomes
    user_id = get_user
    if user_id.present?
     @jsonTransactions = Transaction.getTransactionbyType(user_id, "Income")
     @jsonArr = {"transactions" => @jsonTransactions}
    end
    respond_to do |format|
      format.html {}
      format.json {render json: @jsonArr || "Sorry" }
    end
  end

  def get_user
    session[:user_id] || User.find_by(twitter_user_name: params[:username]).try(:id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.haml
.container
  .row.offset9{style: "text-align: right;"}
    %h4
      =link_to "New Transaction", new_transaction_path
  %h4{style: "text-align: center; color: purple;"}= "Transactions of #{current_user.name}"
  .row
    .span12
      %table.table.table-bordered.table-striped
        %tr
          -Transaction::COLUMNS.each do |col|
            %th{style: "color: orange; text-align: center;"}= col.titleize
        -@jsonTransactions.each do |ts|
          -if ts[:type] == "Income"
            -t_class = "success"
          -else
            -t_class = ts[:type] == "Expense" ? 'error' : 'warning'
          %tr{class: "#{t_class}"}
            -Transaction::COLUMNS.each do |col|
              %td{style: "color: grey; text-align: center;"}= ts[col.to_sym]

app/views/transactions/new.html.haml
.container
  .row{style: "align: center;"}
    %form{method: :post, action: transactions_path}
      %fieldset
        %legend New Transaction
        %label Transaction Type
        %input{placeholder: "Income, Expense or Shared", type: "text", name: "trans_type"}/
        %label Amount
        %input{placeholder: "Enter Amount", type: "text", name: "amount"}/
        %label Vendor
        %input{placeholder: "Vendor Name", type: "text", name: "vendor"}/
        %label Account
        %input{placeholder: "Enter Account Name", type: "text", name: "account"}/
        %label Date
        %input{placeholder: "Enter Transaction Date", type: "text", name: "trans_date"}/
        %label Notes
        %input{placeholder: "Notes", type: "text", name: "notes"}/
        %label Shared Emails
        %input{placeholder: "Enter , separated emails", type: "text", name: "emails"}/
      %button.btn{type: "submit"} Add Transaction
      %br
      %h5= link_to "Show All my Transaction", transactions_path