config/routes.rb
ExpenseAppServer::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'
  get  'welcome/signup', as: 'signup'
  post 'welcome/complete_signup' ,as: 'complete_signup'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :accounts
  resources :shared_transactions do
    get :shared, on: :collection
    get :to_pay, on: :collection
    get :to_be_paid, on: :collection
    post :pay_bill, on: :collection
    post :confirm_payment, on: :collection
  end

  resources :transactions do
    get :expenses, on: :collection
    get :incomes, on: :collection
    get :shared, on: :collection
    get :overview, on: :collection
  end
  resources :vendors
  resources :users

  

end

app/views/layouts/_footer.html.haml
.footer
  %a{href: root_url}Footer for AndroExpense

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "AndroExpense", root_url, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_url
          -if current_user
            %li= link_to "Accounts",  accounts_path
            %li= link_to "Transactions", transactions_path
            %li= link_to "Shared Bill", shared_transactions_path
            %li= link_to "Sign Out #{current_user.name}!", signout_url
          -else
            %li= link_to "Sign in", '/auth/twitter'
- flash.each do |name, msg|
  %h4.flash= content_tag :div, msg, class: name

app/views/layouts/application.html.haml
!!!
%head
  %meta{:charset => "utf-8"}/
  %title ExpenseAppServer
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = yield :stylesheets
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  /[if lt IE 9]
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
%body
  =render "layouts/header"
  =yield
  =render "layouts/footer"