config/routes.rb
ExpenseAppServer::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'
  get  'welcome/signup', as: 'signup'
  post 'welcome/complete_signup' ,as: 'complete_signup'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :accounts
  resources :shared_transactions do
    get :shared, on: :collection
    get :to_pay, on: :collection
    get :to_be_paid, on: :collection
    post :pay_bill, on: :collection
    post :confirm_payment, on: :collection
  end

  resources :transactions do
    get :expenses, on: :collection
    get :incomes, on: :collection
    get :shared, on: :collection
    get :overview, on: :collection
  end
  resources :vendors
  resources :users

  

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id           :integer          not null, primary key
#  display_name :string(255)
#  balance      :decimal(10, 2)   default(0.0)
#  user_id      :integer
#  created_at   :datetime
#  updated_at   :datetime
#  initial_bal  :decimal(10, 2)   default(0.0)
#

class Account < ActiveRecord::Base
  belongs_to :user
  has_many :transactions
  validates_uniqueness_of :display_name, :scope => [:user_id]
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  before_filter :require_authentication
  before_filter :require_email
  

  def create
    name = params["account_name"]
    balance = params["account_balance"]
    Account.find_or_create_by(display_name: name.titleize, user_id: current_user.id, balance: balance.to_f)
    redirect_to accounts_path
  end

  def index
    user_id = session[:user_id]
    @accounts = Account.where(user_id: user_id)
    @total = @accounts.sum :balance
    respond_to do |format|
      format.html {}
      format.json {render json: @accounts}
    end
  end

  def new
  end

  def show
    
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/index.html.haml
.container
  .row.offset9{style: "text-align: right;"}
    %h4
      =link_to "New Account", new_account_path
  %h4{style: "text-align: center; color: purple;"}= "Accounts for #{current_user.name}"
  -@accounts.each do |acc|
    .row
      .span6
        %h2= acc.display_name
      .span6
        %h2= acc.balance
  .row
    .span6
      %h2 Total
    .span6
      %h2= @total

app/views/accounts/new.html.haml
.container
  .row{style: "align: center;"}
    %form{method: :post, action: accounts_path}
      %fieldset
        %legend New Accounts
        %label Name
        %input{placeholder: "Account Name", type: "text", name: "account_name"}/
        %label Balance
        %input{placeholder: "Initial Balance", type: "text", name: "account_balance"}/
      %button.btn{type: "submit"} Add Account
      %br
      %h5= link_to "Show All my Accounts", accounts_path